---
- name: Install kerberose on Raspbian(buster)
  hosts: localhost
  vars_files:
    - vars/vars.yml
  any_errors_fatal: true
  remote_user: root
  become: yes
  become_method: su
  tasks:
  - name: Set timezone
    timezone:
      name: "{{ timeZone }}"
  - name: Set hostname
    hostname: 
      name: "{{ hostName }}"
  - name: Update & upgrade all packages to the latest version (This can take a while)
    apt:
      upgrade: yes
      update_cache: yes
      force_apt_get: yes #Needed for Raspbian(buster) 
      cache_valid_time: 86400 #One day
  - name: Install kerberose server packages
    apt:
      pkg: 
      - krb5-kdc
      - krb5-admin-server
      - krb5-config
      - krb5-user
      - libsasl2-dev
      - libsasl2-modules-gssapi-mit
      - libsasl2-modules
      - libpam-krb5
      - sssd-krb5
  - name: Copy file kdc.conf with owner and permissions
    template:
      src: config/kdc.conf.j2
      dest: /etc/krb5kdc/kdc.conf
      owner: root
      group: root
      mode: '0644'
  - name: Copy file krb5.conf with owner and permissions
    template:
      src: config/krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: '0644'      
  - name: Copy file kadm5.acl with owner and permissions
    template:
      src: config/kadm5.acl.j2
      dest: /etc/krb5kdc/kadm5.acl
      owner: root
      group: root
      mode: '0644'
  - name: Create realm
    shell: kdb5_util create -s -r "{{ realm }}" -P "{{ kDBpw }}"
  - name: start KDC 
    service:
      name: krb5-kdc 
      state: restarted 
      enabled: yes
  - name: start admin server 
    service:
      name: krb5-admin-server 
      state: restarted 
      enabled: yes